// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flicks-designs/BoldSaffron.tsx": () => import("../components/mockups/flicks-designs/BoldSaffron.tsx"),
  "./components/mockups/flicks-designs/DarkCinematic.tsx": () => import("../components/mockups/flicks-designs/DarkCinematic.tsx"),
  "./components/mockups/flicks-designs/GlassGradient.tsx": () => import("../components/mockups/flicks-designs/GlassGradient.tsx")
};
