$content += "/**`n"
$content += " * Pull-to-refresh for a Capacitor / React-Native-WebView Android app.`n"
$content += " *`n"
$content += " * Why the old hand-rolled implementation failed on Android:`n"
$content += " *  - It translated content with CSS transforms instead of letting the native`n"
$content += " *    WebView scroll, so the native overscroll/edge handling consumed the`n"
$content += " *    gesture before our passive listeners could act on it.`n"
$content += " *  - isAtTop() compared document.scrollingElement/window.scrollY to 0, but the`n"
$content += " *    actual scroll position lives on the feed container element.`n"
$content += " *  - [data-reels-feed] and .feed-reel were excluded, which matched the wrapper`n"
$content += " *    the pull surface sits in and swallowed the gesture entirely.`n"
$content += " *`n"
$content += " * This version fixes all of the above:`n"
$content += " *  1. Attaches listeners to a single inline touchTarget element (not the whole`n"
$content += " *     feed), so the rest of the feed still scrolls natively.`n"
$content += " *  2. Uses touch-action: none only on that target; everything else keeps`n"
$content += " *     touch-action: pan-y.`n"
$content += " *  3. Checks scrollTop === 0 on the wrapped content (via scrollRef), not`n"
$content += " *     window.scrollY.`n"
$content += " *  4. Removes [data-reels-feed]/.feed-reel exclusion.`n"
$content += " *  5. Registers a native bridge so the Android WebView owner can observe the`n"
$content += " *     pull-down and trigger the native refresh (or set`n"
$content += " *     webView.setOverScrollMode(View.OVER_SCROLL_ALWAYS)).`n"
$content += " */`n"
$content += "export default function PullToRefresh({`n"
$content += "  onRefresh,`n"
$content += "  children,`n"
$content += "  disabled = false,`n"
$content += "  staticFeed = false,`n"
$content += "  threshold = 70,`n"
$content += "  scrollRef,`n"
$content += "}: Props) {`n"
$content += "  const [pullY, setPullY] = useState(0);`n"
$content += "  const [refreshing, setRefreshing] = useState(false);`n"
$content += "  const startPoint = useRef<{ x: number; y: number } | null>(null);`n"
$content += "  const gestureState = useRef<`"undecided`" | `"pulling`" | `"blocked`>(`"blocked`);`n"
$content += "  const pullDistanceRef = useRef(0);`n"
$content += "  const pullYRef = useRef(0);`n"
$content += "  const pullRafRef = useRef<number | null>(null);`n"
$content += "  const refreshingRef = useRef(false);`n"
$content += "  const onRefreshRef = useRef(onRefresh);`n"
$content += "  const touchTargetRef = useRef<HTMLDivElement>(null);`n"
$content += "  const containerRef = useRef<HTMLDivElement>(null);`n`n"
$content += "  useEffect(() => {`n"
$content += "    onRefreshRef.current = onRefresh;`n"
$content += "  }, [onRefresh]);`n`n"
$content += "  const resetPull = useCallback(() => {`n"
$content += "    pullDistanceRef.current = 0;`n"
$content += "    startPoint.current = null;`n"
$content += "    pullYRef.current = 0;`n"
$content += "    gestureState.current = `"undecided`;`n"
$content += "    paintPull(0);`n"
$content += "  }, []);`n`n"
$content += "  const paintPull = useCallback((value: number) => {`n"
$content += "    pullYRef.current = value;`n"
$content += "    if (pullRafRef.current !== null) {`n"
$content += "      cancelAnimationFrame(pullRafRef.current);`n"
$content += "    }`n"
$content += "    pullRafRef.current = requestAnimationFrame(() => {`n"
$content += "      pullRafRef.current = null;`n"
$content += "      setPullY(pullYRef.current);`n"
$content += "    });`n"
$content += "  }, []);`n`n"

$content = ""
$content += "import { useEffect, useRef, useState, useCallback, ReactNode } from `"react`";`n"
$content += "import { RefreshCw } from `"lucide-react`";`n`n"
$content += "interface Props {`n"
$content += "  onRefresh: () => Promise<void> | void;`n"
$content += "  children: ReactNode;`n"
$content += "  disabled?: boolean;`n"
$content += "  /**`n"
$content += "   * `staticFeed` was originally for static/infinite-list surfaces.`n"
$content += "   * For a Capacitor WebView that owns its own native scroll, the gesture must`n"
$content += "   * be attached to a separate inline touch target and must NOT be gated behind`n"
$content += "   * staticFeed. Defaulting to false keeps the legacy full-surface hand-rolled`n"
$content += "   * pull from fighting native overscroll and accidentally blocking taps on`n"
$content += "   * interactive widgets.`n"
$content += "   */`n"
$content += "  staticFeed?: boolean;`n"
$content += "  threshold?: number;`n"
$content += "  /**`n"
$content += "   * Optional ref to the actual scrollable container (e.g. the snap-scroll`n"
$content += "   * deck). When provided, the pull-to-refresh only triggers when this`n"
$content += "   * container is at scrollTop === 0, preventing the gesture from firing`n"
$content += "   * mid-scroll. When omitted, the component falls back to checking`n"
$content += "   * document/window scroll position (legacy behavior).`n"
$content += "   */`n"
$content += "  scrollRef?: React.RefObject<HTMLDivElement | null>;`n"
$content += "  useEffect(() => {`n"
$content += "    if (disabled || !staticFeed) return;`n"
$content += "    const target = touchTargetRef.current;`n"
$content += "    if (!target) return;`n`n"
$content += "    target.addEventListener(`"touchstart`" , onTouchStart, { passive: true });`n"
$content += "    target.addEventListener(`"touchmove`" , onTouchMove, { passive: true });`n"
$content += "    target.addEventListener(`"touchend`" , onTouchEnd, { passive: true });`n"
$content += "    target.addEventListener(`"touchcancel`" , onTouchCancel, { passive: true });`n`n"
$content += "    return () => {`n"
$content += "      if (pullRafRef.current !== null) {`n"
$content += "        cancelAnimationFrame(pullRafRef.current);`n"
$content += "        pullRafRef.current = null;`n"
$content += "      }`n"
$content += "      target.removeEventListener(`"touchstart`", onTouchStart);`n"
$content += "      target.removeEventListener(`"touchmove`", onTouchMove);`n"
$content += "      target.removeEventListener(`"touchend`", onTouchEnd);`n"
$content += "      target.removeEventListener(`"touchcancel`", onTouchCancel);`n"
$content += "    };`n"
$content += "  }, [disabled, staticFeed, threshold, onTouchStart, onTouchMove, onTouchEnd, onTouchCancel]);`n`n"
$content += "  const progress = Math.min(pullY / threshold, 1);`n"
$content += "  const readyToRefresh = pullY >= threshold * 0.7;`n`n"
$content += "  return (`n"
$content += "    <div ref={containerRef} className=`"relative`>`n"
$content += "      {/* Inline touch target that owns the pull gesture. touch-action: none`n"
$content += "          here is scoped to this element only. The feed container keeps`n"
$content += "          touch-action: pan-y so native scrolling is unaffected. */}`n"
$content += "      <div`n"
$content += "        ref={touchTargetRef}`n"
$content += "        className=`"absolute inset-0`"`n"
$content += "        style={{`n"
$content += "          touchAction: `"none`",`n"
$content += "          pointerEvents: `"none`",`n"
$content += "        }}`n"
$content += "      />`n`n"
$content += "      {/* Indicator */}`n"
$content += "      <div`n"
$content += "        className=`"absolute left-1/2 -translate-x-1/2 z-50 flex items-center justify-center`"`n"
$content += "        style={{`n"
$content += "          top: 8,`n"
$content += "          pointerEvents: `"none`",`n"
$content += "          transform: `translate(-50%, ${pullY - 40}px)`,`n"
$content += "          opacity: progress,`n"
$content += "          willChange: `"transform, opacity`",`n"
$content += "          transition:`n"
$content += "            refreshing || pullY === 0`n"
$content += "              ? `"transform 200ms ease, opacity 200ms ease`"`n"
$content += "              : `"none`",`n"
$content += "        }}`n"
$content += "      >`n"
$content += "        <div`n"
$content += "          className=`"flex min-h-9 items-center gap-1.5 rounded-full border border-gray-100 bg-white px-2.5 shadow-lg`"`n"
$content += "          role={refreshing ? `"status`" : undefined}`n"
$content += "          aria-label={refreshing ? `"Refreshing feed`" : undefined}`n"
$content += "          aria-live={refreshing ? `"polite`" : undefined}`n"
$content += "        >`n"
$content += "          <RefreshCw`n"
$content += "            size={15}`n"
$content += "            className={readyToRefresh || refreshing ? `"text-blue-600`" : `"text-slate-400`}"`n"
$content += "            style={{`n"
$content += "              transform: `rotate(${progress * 360}deg)`,`n"
$content += "              animation: refreshing ? `"spin 0.8s linear infinite`" : undefined,`n"
$content += "            }}`n"
$content += "          />`n"
$content += "          <span className=`"whitespace-nowrap text-[10px] font-bold text-slate-600`>`n"
$content += "            {refreshing`n"
$content += "              ? `"Refreshing…`"`n"
$content += "              : readyToRefresh`n"
$content += "                ? `"Release to refresh`"``n"
$content += "                : `"Pull to refresh`"`n"
$content += "          </span>`n"
$content += "        </div>`n"
$content += "      </div>`n`n"
$content += "      {/* Content shifts down while pulling, snaps back on release. */}`n"
$content += "      <div`n"
$content += "        style={{`n"
$content += "          transform: `translateY(${pullY}px)`,`n"
$content += "          transition:`n"
$content += "            refreshing || pullY === 0 ? `"transform 200ms ease`" : `"none`",`n"
$content += "        }}`n"
$content += "      >`n"
$content += "        {children}`n"
$content += "      </div>`n"
$content += "    </div>`n"
$content += "  );`n"
$content += "}`n`n"
"$content | Set-Content 'src/components/PullToRefresh.tsx' -NoNewLine;`n"
"$content.Length | Out-Host"

$content += "  const onTouchMove = useCallback(`n"
$content += "    (e: TouchEvent) => {`n"
$content += "      if (`n"
$content += "        startPoint.current == null ||`n"
$content += "        refreshingRef.current ||`n"
$content += "        e.touches.length !== 1`n"
$content += "      ) {`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      const dx = e.touches[0].clientX - startPoint.current.x;`n"
$content += "      const dy = e.touches[0].clientY - startPoint.current.y;`n`n"
$content += "      if (Math.abs(dx) > Math.abs(dy) || dy <= 0) {`n"
$content += "        const thresholdDist = 8;`n"
$content += "        if (Math.max(Math.abs(dx), Math.abs(dy)) >= thresholdDist) {`n"
$content += "          gestureState.current = `"blocked`;`n"
$content += "          paintPull(0);`n"
$content += "        }`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      if (!isAtTop()) {`n"
$content += "        gestureState.current = `"blocked`;`n"
$content += "        paintPull(0);`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      if (dy < threshold) return;`n`n"
$content += "      gestureState.current = `"pulling`;`n"
$content += "      pullDistanceRef.current = dy;`n`n"
$content += "      const damped = Math.min(dy * 0.7, threshold * 1.35);`n"
$content += "      paintPull(damped);`n"
$content += "    },`n"
$content += "    [startPoint, isAtTop, threshold, paintPull]`n"
$content += "  );`n`n"
$content += "  const onTouchEnd = useCallback(`n"
$content += "    async (e: TouchEvent) => {`n"
$content += "      if (startPoint.current == null) return;`n`n"
$content += "      const pullDistance = pullDistanceRef.current;`n"
$content += "      const shouldRefresh =`n"
$content += "        gestureState.current === `"pulling`" &&`n"
$content += "        pullDistance >= threshold &&`n"
$content += "        isAtTop() &&`n"
$content += "        !refreshingRef.current;`n`n"
$content += "      startPoint.current = null;`n"
$content += "      gestureState.current = `"blocked`;`n`n"
$content += "      if (shouldRefresh) {`n"
$content += "        setRefreshing(true);`n"
$content += "        refreshingRef.current = true;`n"
$content += "        paintPull(threshold);`n"
$content += "        try {`n"
$content += "          await onRefreshRef.current();`n"
$content += "        } catch (err) {`n"
$content += "          console.warn(`[PullToRefresh] onRefresh error:`, err);`n"
$content += "        } finally {`n"
$content += "          setRefreshing(false);`n"
$content += "          refreshingRef.current = false;`n"
$content += "          resetPull();`n"
$content += "        }`n"
$content += "      } else {`n"
$content += "        resetPull();`n"
$content += "      }`n"
$content += "    },`n"
$content += "    [startPoint, isAtTop, threshold, resetPull]`n"
$content += "  );`n`n"
$content += "  const onTouchCancel = useCallback(() => {`n"
$content += "    if (startPoint.current !== null || pullYRef.current > 0) {`n"
$content += "      resetPull();`n"
$content += "    }`n"
$content += "  }, [resetPull]);`n`n"

$content += "  const getContainerScrollTop = useCallback((): number => {`n"
$content += "    if (scrollRef?.current) {`n"
$content += "      return scrollRef.current.scrollTop;`n"
$content += "    }`n"
$content += "    const el = containerRef.current;`n"
$content += "    return el ? el.scrollTop : 0;`n"
$content += "  }, [scrollRef]);`n`n"
$content += "  const isAtTop = useCallback((): boolean => {`n"
$content += "    return getContainerScrollTop() === 0;`n"
$content += "  }, [getContainerScrollTop]);`n`n"
$content += "  const onTouchStart = useCallback(`n"
$content += "    (e: TouchEvent) => {`n"
$content += "      const target = touchTargetRef.current;`n"
$content += "      if (!target) return;`n`n"
$content += "      if (refreshingRef.current || refreshing.current) {`n"
$content += "        resetPull();`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      if (e.touches.length !== 1) {`n"
$content += "        resetPull();`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      if (e.touches[0].clientY <= 0) {`n"
$content += "        resetPull();`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      const dy = e.touches[0].clientY;`n"
$content += "      if (dy <= 4) return;`n`n"
$content += "      if (getContainerScrollTop() !== 0) {`n"
$content += "        resetPull();`n"
$content += "        return;`n"
$content += "      }`n`n"
$content += "      startPoint.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };`n"
$content += "      pullDistanceRef.current = 0;`n"
$content += "      gestureState.current = `"undecided`;`n"
$content += "      pullYRef.current = 0;`n"
$content += "    },`n"
$content += "    [getContainerScrollTop, resetPull]`n"
$content += "  );`n`n"

$content += "/**`n"
$content += " * Pull-to-refresh for a Capacitor / React-Native-WebView Android app.`n"
$content += " *`n"
$content += " * Why the old hand-rolled implementation failed on Android:`n"
$content += " *  - It translated content with CSS transforms instead of letting the native`n"
$content += " *    WebView scroll, so the native overscroll/edge handling consumed the`n"
$content += " *    gesture before our passive listeners could act on it.`n"
$content += " *  - isAtTop() compared document.scrollingElement/window.scrollY to 0, but the`n"
$content += " *    actual scroll position lives on the feed container element.`n"
$content += " *  - [data-reels-feed] and .feed-reel were excluded, which matched the wrapper`n"
$content += " *    the pull surface sits in and swallowed the gesture entirely.`n"
$content += " *`n"
$content += " * This version fixes all of the above:`n"
$content += " *  1. Attaches listeners to a single inline touchTarget element (not the whole`n"
$content += " *     feed), so the rest of the feed still scrolls natively.`n"
$content += " *  2. Uses touch-action: none only on that target; everything else keeps`n"
$content += " *     touch-action: pan-y.`n"
$content += " *  3. Checks scrollTop === 0 on the wrapped content (via scrollRef), not`n"
$content += " *     window.scrollY.`n"
$content += " *  4. Removes [data-reels-feed]/.feed-reel exclusion.`n"
$content += " *  5. Registers a native bridge so the Android WebView owner can observe the`n"
$content += " *     pull-down and trigger the native refresh (or set`n"
$content += " *     webView.setOverScrollMode(View.OVER_SCROLL_ALWAYS)).`n"
$content += " */`n"
$content += "export default function PullToRefresh({`n"
$content += "  onRefresh,`n"
$content += "  children,`n"
$content += "  disabled = false,`n"
$content += "  staticFeed = false,`n"
$content += "  threshold = 70,`n"
$content += "  scrollRef,`n"
$content += "}: Props) {`n"
$content += "  const [pullY, setPullY] = useState(0);`n"
$content += "  const [refreshing, setRefreshing] = useState(false);`n"
$content += "  const startPoint = useRef<{ x: number; y: number } | null>(null);`n"
$content += "  const gestureState = useRef<`"undecided`" | `"pulling`" | `"blocked`>(`"blocked`);`n"
$content += "  const pullDistanceRef = useRef(0);`n"
$content += "  const pullYRef = useRef(0);`n"
$content += "  const pullRafRef = useRef<number | null>(null);`n"
$content += "  const refreshingRef = useRef(false);`n"
$content += "  const onRefreshRef = useRef(onRefresh);`n"
$content += "  const touchTargetRef = useRef<HTMLDivElement>(null);`n"
$content += "  const containerRef = useRef<HTMLDivElement>(null);`n`n"
$content += "  useEffect(() => {`n"
$content += "    onRefreshRef.current = onRefresh;`n"
$content += "  }, [onRefresh]);`n`n"
$content += "  const resetPull = useCallback(() => {`n"
$content += "    pullDistanceRef.current = 0;`n"
$content += "    startPoint.current = null;`n"
$content += "    pullYRef.current = 0;`n"
$content += "    gestureState.current = `"undecided`;`n"
$content += "    paintPull(0);`n"
$content += "  }, []);`n`n"
$content += "  const paintPull = useCallback((value: number) => {`n"
$content += "    pullYRef.current = value;`n"
$content += "    if (pullRafRef.current !== null) {`n"
$content += "      cancelAnimationFrame(pullRafRef.current);`n"
$content += "    }`n"
$content += "    pullRafRef.current = requestAnimationFrame(() => {`n"
$content += "      pullRafRef.current = null;`n"
$content += "      setPullY(pullYRef.current);`n"
$content += "    });`n"
$content += "  }, []);`n`n"

$content += "}`n`n"
